title: Varathalingam Mayouran # your name (or website title) here
logo: "photo_mayouran_linkedin.jpg" # your photo (or logo) here
description: > 
  Computer Engineer graduate from EFREI Paris with a passion for Data and Artificial Intelligence. I am currently employed in a permanent position at Air France as a Data Analyst.
  
  
  <a href="https://www.linkedin.com/in/mayouran-varathalingam/">View My LinkedIn Profile</a> 
  



plugins:
- jekyll-remote-theme
