title: Varathalingam Mayouran # your name (or website title) here
logo: "photo_mayouran_linkedin.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Engineer graduate from EFREI Paris with a passion for Data and Artificial Intelligence (Machine Learning & Deep Learning).With multiple experiences in the data field, I am currently employed in a permanent position at Air France as a Data Analyst.
  <br><br>
  <a href="https://www.linkedin.com/in/mayouran-varathalingam/">View My LinkedIn Profile</a> 


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
